# Generated by Django 5.0.1 on 2024-01-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aluguel', models.DateTimeField(auto_now_add=True)),
                ('data_devolução', models.DateTimeField(auto_now=True)),
                ('taxa_de_entrega', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.IntegerField()),
                ('quantidade_alugada', models.IntegerField()),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.transação')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.IntegerField()),
                ('quantidade_alugada', models.IntegerField()),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.transação')),
            ],
        ),
    ]
